# backend/Dockerfile

# Usar uma imagem base do Node.js
FROM node:14

# Diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar package.json e package-lock.json
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o código fonte
COPY . .

# Expor a porta do servidor
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
